#!/usr/bin/env bash
# Build the isolated amdgpu-sim-tools conda environment (one key).
#
# The environment carries no packages of its own: it is a pure
# activation wrapper that puts the simulator toolchain first on PATH
# and gives it private caches, so `conda activate AMDGPU-CDNA4-SIM`
# yields a shell where rocm-smi and gem5-session
# just work while the base shell stays untouched.  Regenerating is
# idempotent and instant (a few symlinks and two shell scripts).
#
# Usage: bash scripts/make_amdgpu_tools_env.sh
set -euo pipefail

ROOT="/home/zhaosiying/zcode-lane"
TOOLS_ENV="${SAGR_TOOLS_ENV_TARGET:-${HOME}/miniforge3/envs/AMDGPU-CDNA4-SIM}"
ROCM_PREFIX="${ROOT}/env/conda/rocm-pytorch-v3-fa8414cce688f934f538163621423376c2542acff3e4d3e403df4340d90fcd6d"
PRODUCT_PREFIX="${ROOT}/env/rocm/product-v1-1c3b9563dbf3e08265b909068599abdd6a16bfa340ebc1635b2365b87c7fd4c8"
RUNTIME_BUILD="${ROOT}/projects/self-amdgpu-runtime/build/cp28-runtime-clang"
ROCR_LIB="${ROOT}/build/rocr-stage-zcode/lib"
TOPOLOGY="${PRODUCT_PREFIX}/share/self-amdgpu-runtime/hsakmt-topology"
GEMSIM_SMI="${ROOT}/tools/gemsim_smi.py"

for f in "${ROCM_PREFIX}/bin/python" "${RUNTIME_BUILD}/libself_amdgpu_runtime.so.1" \
         "${ROCR_LIB}/libhsa-runtime64.so.1" "${GEMSIM_SMI}" "${ROOT}/tools/gemsim_smi_publish.py" \
         "${ROOT}/build/rocr_logging_preload.so" \
         "${ROOT}/projects/gem5/build/VEGA_X86/gem5.opt" \
         "${ROOT}/tools/softmax_demo.py" \
         "${ROOT}/scripts/gem5_session_control.sh" \
         "${TOPOLOGY}"; do
  [[ -e $f ]] || { echo "missing prerequisite: $f" >&2; exit 2; }
done

mkdir -p "${TOOLS_ENV}/bin" "${TOOLS_ENV}/etc/conda/activate.d" \
         "${TOOLS_ENV}/etc/conda/deactivate.d" \
         "${TOOLS_ENV}/var/triton-cache" "${TOOLS_ENV}/var/xdg"

# conda only recognizes a prefix as an environment when conda-meta/
# exists; a history file with the env name is enough.
mkdir -p "${TOOLS_ENV}/conda-meta"
printf 'name: amdgpu-sim-tools\n==> 2026-08-24 bootstrap\n# cmd: make_amdgpu_tools_env.sh\n' \
  > "${TOOLS_ENV}/conda-meta/history"

# ---- activation / deactivation -------------------------------------------------
cat > "${TOOLS_ENV}/etc/conda/activate.d/amdgpu-sim-tools.sh" <<ACT
# Generated by scripts/make_amdgpu_tools_env.sh -- do not edit by hand.
_amdgpu_sim_tools_prefix="${TOOLS_ENV}"
_amdgpu_sim_rocm="${ROCM_PREFIX}"

# Tool binaries first: this environment's wrappers, then the tools venv
# shims, then the ROCm pytorch prefix's own tools (python, rocminfo...).
export PATH="\${_amdgpu_sim_tools_prefix}/bin:\${_amdgpu_sim_rocm}/bin:\${PATH}"

# Runtime libraries in dependency order: the worktree's rebuilt ROCr
# stage and the runtime build with the simulator fixes first, then the
# pinned prefix's own stack (system-runtime for libmpi_cxx, the ROCm
# sysroot for the compiler/runtime libraries, the prefix lib itself).
export LD_LIBRARY_PATH="${RUNTIME_BUILD}:${ROCR_LIB}:\${_amdgpu_sim_rocm}/system-runtime/usr/lib/x86_64-linux-gnu:\${_amdgpu_sim_rocm}/rocm-sysroot/opt/rocm-7.2.3/lib:\${_amdgpu_sim_rocm}/rocm-sysroot/opt/rocm-7.2.3/lib/rocm_sysdeps/lib:\${_amdgpu_sim_rocm}/lib:\${LD_LIBRARY_PATH:-}"
export LD_PRELOAD="${ROOT}/build/rocr_logging_preload.so:${ROCR_LIB}/libhsa-runtime64.so.1\${LD_PRELOAD:+:\${LD_PRELOAD}}"

# The simulated device stack.
export ROCM_SIM_ROOT="${PRODUCT_PREFIX}"
export HSA_PATH="${PRODUCT_PREFIX}"
export HSA_MODEL_LIB="${RUNTIME_BUILD}/libself_amdgpu_hsakmt_model.so.1"
# The product activation's two hard requirements: this WSL host exposes
# /dev/dxg, and without this flag the ROCr thunk walker tries librocdxg
# and never reaches the model library; interrupts likewise must be off.
export HSA_ENABLE_DXG_DETECTION=0
export HSA_ENABLE_INTERRUPT=0
export HIP_PLATFORM=amd
export HSA_MODEL_TOPOLOGY="${TOPOLOGY}"
export SAGR_ROCR_LIBRARY_DIR="${ROCR_LIB}"
export SAGR_TOOLS_TOPOLOGY="${TOPOLOGY}"

# Private caches so this shell never poisons (or reads) another
# session's Triton compile results.
export TRITON_CACHE_DIR="\${_amdgpu_sim_tools_prefix}/var/triton-cache"
export XDG_CACHE_HOME="\${_amdgpu_sim_tools_prefix}/var/xdg"

# Session plumbing for the standalone simulator.  The session lives
# under /tmp: gem5's evidence files refuse paths containing symlinks
# (O_NOFOLLOW on every component), and this prefix's env/conda is one.
export SAGR_TOOLS_SESSION_DIR="/tmp/amdgpu-sim-tools-session"
export SAGR_TOOLS_SESSION_ENV="/tmp/amdgpu-sim-tools-session/session.env"
[[ -f "\${SAGR_TOOLS_SESSION_ENV}" ]] && source "\${SAGR_TOOLS_SESSION_ENV}"

# Make plain 'python' resolve inside this activation even when the base
# conda would otherwise shadow it.
hash -r
ACT

cat > "${TOOLS_ENV}/etc/conda/deactivate.d/amdgpu-sim-tools.sh" <<DEACT
# Generated by scripts/make_amdgpu_tools_env.sh -- do not edit by hand.
# Conda restores PATH/LD_* it snapshot at activation; the variables this
# environment introduced itself are cleared here.
unset ROCM_SIM_ROOT HSA_PATH HSA_MODEL_LIB HSA_MODEL_TOPOLOGY \
      SAGR_ROCR_LIBRARY_DIR SAGR_TOOLS_TOPOLOGY TRITON_CACHE_DIR \
      XDG_CACHE_HOME SAGR_TOOLS_SESSION_DIR SAGR_TOOLS_SESSION_ENV \
      SAGR_GENERIC_BRIDGE_ENDPOINT 2>/dev/null || true
hash -r
DEACT

# ---- tool wrappers ---------------------------------------------------------------

# rocm-smi: the product's gemsim_smi under its classic name.
cat > "${TOOLS_ENV}/bin/rocm-smi" <<SMI
#!/bin/sh
exec "${ROCM_PREFIX}/bin/python" "${GEMSIM_SMI}" "\$@"
SMI

# gem5-session: start/stop/restart/status for the standalone simulator.
ln -sfn "${ROOT}/scripts/gem5_session_control.sh" "${TOOLS_ENV}/bin/gem5-session"

# triton-softmax: one-shot Triton kernel on the simulated GPU, checked
# against a CPU reference (exit 0/1).
cat > "${TOOLS_ENV}/bin/triton-softmax" <<SMX
#!/bin/sh
exec "${ROCM_PREFIX}/bin/python" "${ROOT}/tools/softmax_demo.py" "\$@"
SMX

chmod +x "${TOOLS_ENV}/bin/rocm-smi" "${TOOLS_ENV}/bin/triton-softmax" \
        "${ROOT}/scripts/gem5_session_control.sh" "${ROOT}/tools/softmax_demo.py"

echo "AMDGPU-CDNA4-SIM environment ready: ${TOOLS_ENV}"
echo "  conda activate AMDGPU-CDNA4-SIM     (or: conda activate ${TOOLS_ENV})"
echo '  then:  rocm-smi | gem5-session start 1 | python tools/softmax_demo.py'
