#!/usr/bin/env bash
# One runner for every acceptance lane: {SGLang, vLLM} x {TP1, TP2, TP16}.
#
#   scripts/run_engine_lane.sh --engine sglang --tp 1 <logfile>
#   scripts/run_engine_lane.sh --engine vllm   --tp 16 <logfile>
#
# This replaces six near-identical scripts. They had drifted apart in ways that
# cost real time: only one of them prepended the freshly built runtime to
# LD_LIBRARY_PATH, so the other silently ran a stale library, and only one
# pinned the HEAD product, so the other loaded a ROCm build predating every
# fast-copy commit. A single runner makes such a divergence impossible to
# introduce by accident, and the identity header below makes it impossible to
# miss if it happens anyway.
#
# Both engines are stock upstream. Nothing here registers a project operator,
# replaces a model or layer, or patches engine source; the only adaptation is
# to the self-runtime interface, which is the thing under test.
set -u

ROOT=/home/zhaosiying/amdgpu-sim
cd "$ROOT"

engine=""
tp=""
model=""
dummy_weights=0
capsule=""
# Which simulator to run. The optimised build plus --functional-fast is
# ~3x faster on the representative kernel and was shown to produce
# byte-identical results and an identical retired-dispatch sequence, but
# the accurate binary stays the default so a lane opts in explicitly.
gem5="${ROOT}/projects/gem5/build/VEGA_X86/gem5.opt"

while (($#)); do
  case "$1" in
    --engine) engine=${2:?}; shift 2 ;;
    --tp) tp=${2:?}; shift 2 ;;
    --model) model=${2:?}; shift 2 ;;
    --dummy-weights) dummy_weights=1; shift ;;
    --gem5) gem5=${2:?}; shift 2 ;;
    --fast) gem5="${ROOT}/projects/gem5/build/VEGA_X86/gem5.opt.fastwrap"; shift ;;
    # Run a standalone capsule instead of an engine, under this script's exact
    # environment and NVML isolation. A capsule that rebuilds the environment
    # for itself drifts from the lanes and then proves nothing about them --
    # and outside the isolation it dies immediately with hsa_init 4104, which
    # has already cost several confused debugging attempts.
    --capsule) capsule=${2:?}; shift 2 ;;
    *) break ;;
  esac
done

log="${1:?usage: run_engine_lane.sh --engine E --tp N [--model M] [--dummy-weights] <logfile>}"

if [[ -z $capsule ]]; then
  case "$engine" in
    sglang|vllm) ;;
    *) printf 'engine must be sglang or vllm\n' >&2; exit 2 ;;
  esac
elif [[ ! -r $capsule ]]; then
  printf 'capsule is not readable: %s\n' "$capsule" >&2; exit 2
fi
if ! [[ $tp =~ ^[0-9]+$ ]] || (( tp < 1 )); then
  printf 'tp must be a positive integer\n' >&2; exit 2
fi

# The ladder pairs a model with a degree of parallelism: 0.8B carries TP1 and
# TP2, 9B carries TP16.
if [[ -z $model ]]; then
  if (( tp >= 16 )); then model="${ROOT}/models/Qwen3.5-9B"; else model="${ROOT}/models/Qwen3.5-0.8B"; fi
fi
if [[ ! -d $model ]]; then
  printf 'model directory is absent: %s\n' "$model" >&2
  exit 2
fi

# --- environment ------------------------------------------------------------
PREFIX="${ROOT}/env/conda/rocm-pytorch-v3-fa8414cce688f934f538163621423376c2542acff3e4d3e403df4340d90fcd6d"
# shellcheck disable=SC1091
source "${PREFIX}/etc/conda/activate.d/amdgpu-sim-rocm-pytorch.sh"
# shellcheck disable=SC1091
source "${ROOT}/scripts/fastcopy_mode.sh" fast

# The activate script of this prefix exports the product that predates every
# fast-copy commit. Rewriting the paths is what makes the run test the code
# that is actually under review -- a run that skipped this step once spent 70
# minutes proving nothing.
STALE="${ROOT}/env/rocm/product-v1-f76db762609b346cb83b920cc82cd2b734b75cd31b8562e6536ad81275fe17e1"
HEAD_PRODUCT="${ROOT}/env/rocm/product-v1-4d9d40454031c7345f25da81b6781995b09a3b10e4dd66026e019306fc7ee39b"
RUNTIME_BUILD="${ROOT}/projects/self-amdgpu-runtime/build/cp28-runtime-clang"

export LD_LIBRARY_PATH="$(echo "${LD_LIBRARY_PATH}" | sed "s|${STALE}|${HEAD_PRODUCT}|g")"
export HSA_PATH="${HEAD_PRODUCT}"
export ROCM_SIM_ROOT="${HEAD_PRODUCT}"
# The topology declares how many GPUs the simulated stack exposes, and the
# product ships a single-GPU one. A tensor-parallel engine calls
# set_device(rank) on every rank, so TP2 dies immediately with
#
#   torch.AcceleratorError: CUDA error: invalid device ordinal
#
# unless the topology has that many GPU nodes. Topologies are generated by
# projects/self-amdgpu-runtime/tools/hsakmt-model-topology.py; the model
# supports up to SAGR_HSAKMT_MODEL_MAXIMUM_VISIBLE_GPUS = 16, which is exactly
# what the TP16 rung needs.
if (( tp > 1 )); then
  export HSA_MODEL_TOPOLOGY="${ROOT}/artifacts/topology/gpu-${tp}"
  if [[ ! -d $HSA_MODEL_TOPOLOGY ]]; then
    python3 "${ROOT}/projects/self-amdgpu-runtime/tools/hsakmt-model-topology.py" \
      --output-dir "$HSA_MODEL_TOPOLOGY" --gpu-count "$tp" >/dev/null || {
        printf 'could not generate a %s-GPU topology\n' "$tp" >&2; exit 2; }
  fi
else
  export HSA_MODEL_TOPOLOGY="${HEAD_PRODUCT}/share/self-amdgpu-runtime/hsakmt-topology"
fi

# Order matters and is deliberate. Only the freshly built runtime is prepended,
# so the self-runtime under test is the one that loads. The product's lib
# directory is deliberately NOT prepended.
#
# It is tempting to prepend it -- doing so makes HIP resolve to the HEAD
# product's libamdhip64 instead of the stock ROCm 7.2.3 that sits earlier on
# the activate script's path, which looks more consistent. It is not: PyTorch's
# precompiled device code in this prefix was built against ROCm 7.2.3, and
# loading the HEAD product's HIP invalidates every one of those code objects.
# Both engines then die at the first device allocation with
#
#   torch.AcceleratorError: CUDA error: device kernel image is invalid
#   (hipErrorInvalidImage)
#
# The combination that works, and that every successful run here has used, is
# stock ROCm 7.2.3 HIP plus the HEAD product's ROCr -- ROCr resolves to the
# product regardless of order because no other libhsa-runtime64.so.1 exists
# under the prefix. The identity gate below records what actually loaded.
export LD_LIBRARY_PATH="${RUNTIME_BUILD}:${LD_LIBRARY_PATH}"
export LD_PRELOAD="${ROOT}/build/rocr_logging_preload.so:$(echo "${LD_PRELOAD:-}" | sed "s|${STALE}|${HEAD_PRODUCT}|g")"
export LD_PRELOAD="${LD_PRELOAD%:}"
export HSA_MODEL_LIB="${RUNTIME_BUILD}/libself_amdgpu_hsakmt_model.so.1"

# Device discovery belongs to this product, and some consumers reach it by
# running a *tool* rather than by calling a library: aiter resolves the live
# gfx arch with shutil.which("rocminfo") and parses its output, and documents
# that get_gfx_runtime() ignores GPU_ARCHS, so no environment variable can
# stand in. Upstream rocminfo cannot answer here -- it needs the amdgpu kernel
# module, and on this host it prints "hsa_init Failed" with no gfx line at all,
# which made aiter deduce an arch of [''] and abort a lane after 1447 retired
# dispatches. Put the product's own rocminfo first on PATH. The product prefix
# is immutable and the upstream sysroot is not ours to overwrite, so the shim
# lives in a directory this runner owns and regenerates.
TOOL_SHIM="${ROOT}/artifacts/tool-shim"
mkdir -p "$TOOL_SHIM"
ln -sfn "${RUNTIME_BUILD}/sagr-rocminfo" "${TOOL_SHIM}/rocminfo"
export PATH="${TOOL_SHIM}:${PATH}"

export SAGR_MANAGED_GEM5="$gem5"
export SAGR_MANAGED_GEM5_CONFIG="${ROOT}/projects/gem5/configs/example/gemsim/host_dispatch.py"
export SAGR_MANAGED_REPO_ROOT="${ROOT}"
# SAGR_MANAGED_RUN_ROOT is inherited from the lane supervisor. It confines this
# lane's simulators to their own directory so progress accounting and cleanup
# can tell them apart from another lane's; see scripts/lane_ownership.sh.

export TRITON_DEFAULT_BACKEND=gemsim_hip
export TRITON_BACKENDS_IN_TREE=0
export GEMSIM_HIP_AUTOTUNE_MODE=correctness
export TRITON_CACHE_AUTOTUNING=1
# ROCr refuses to run multi-agent collectives without this and aborts with
#   [FATAL ERROR]: HSA_NO_SCRATCH_RECLAIM=1 must be set
# It is an upstream-documented ROCm setting, not a project workaround.
export HSA_NO_SCRATCH_RECLAIM=1
unset SAGR_OPENCL_ENDPOINT SAGR_OPENCL_SOCKET SAGR_OPENCL_GEM5_EXTERNAL
unset CUDA_VISIBLE_DEVICES

if [[ $engine == sglang ]]; then
  export PYTHONPATH="${ROOT}/projects/sglang-0.5.17:${ROOT}/env/sglang-overlay-cp312"
  export SGLANG_USE_AITER=1
  export FLA_CACHE_RESULTS=1
else
  # vLLM runs on the formal Triton path: the unchanged upstream AMD hip
  # compiler and driver, which is what GOAL.md designates and what leaves
  # gemsim_hip as a regression/migration backend only.
  #
  # It must not merely be *preferred* here, it must be the only backend
  # present. GemsimHIPDriver.is_active() gates itself on
  # TRITON_DEFAULT_BACKEND, but that does not make the in-tree amd driver
  # inactive, so both claim the same device. Triton's own selector is happy --
  # it consults TRITON_DEFAULT_BACKEND directly -- but any consumer that counts
  # active drivers is not: vLLM requires exactly one, and on finding two it
  # disables Triton outright, after which the run dies at the first use with
  #   AttributeError: module 'triton' has no attribute 'next_power_of_2'
  # having already retired 447 dispatches. Discovering only in-tree backends
  # leaves exactly one active driver for every consumer.
  export TRITON_BACKENDS_IN_TREE=1
  # Name the in-tree backend explicitly: the shared block above selects
  # gemsim_hip, which is no longer discovered here, and Triton rejects an
  # unknown TRITON_DEFAULT_BACKEND outright.
  export TRITON_DEFAULT_BACKEND=amd
  export PYTHONPATH=""
  # Empty allowlist: vllm/plugins/__init__.py loads a plugin only when its name
  # is in VLLM_PLUGINS, and an empty value parses to a list matching nothing.
  # This is the hard kill switch for both vllm.platform_plugins and
  # vllm.general_plugins, so no project operator can register even by accident.
  export VLLM_PLUGINS=
  export VLLM_ENABLE_V1_MULTIPROCESSING=0
  export VLLM_WORKER_MULTIPROC_METHOD=spawn
  export VLLM_NO_USAGE_STATS=1
  export HIP_VISIBLE_DEVICES=$(seq -s, 0 $((tp - 1)))
fi

# --- identity ---------------------------------------------------------------
{
  echo "# lane"
  echo "engine=${engine} tp=${tp} model=${model} dummy_weights=${dummy_weights}"
  echo "run_root=${SAGR_MANAGED_RUN_ROOT:-<unset>}"
  echo "topology=${HSA_MODEL_TOPOLOGY} gpu_nodes=$(( $(ls "${HSA_MODEL_TOPOLOGY}/nodes" | wc -l) - 1 ))"
  echo "# identity"
  echo "repo_head=$(git -C "$ROOT" rev-parse HEAD)"
  echo "rocm_systems_head=$(git -C "${ROOT}/projects/rocm-systems" rev-parse HEAD)"
  echo "product=${HEAD_PRODUCT}"
  echo "runtime_sha256=$(sha256sum "${RUNTIME_BUILD}/libself_amdgpu_runtime.so.0.8.0" | cut -d' ' -f1)"
  echo "model_lib_sha256=$(sha256sum "${HSA_MODEL_LIB}" | cut -d' ' -f1)"
  echo "gem5=${SAGR_MANAGED_GEM5}"
  echo "gem5_sha256=$(sha256sum "${SAGR_MANAGED_GEM5}" | cut -d' ' -f1)"
  echo "fastcopy=HSA_ENABLE_DTIF_FAST_COPY=${HSA_ENABLE_DTIF_FAST_COPY} SAGR_HSAKMT_MODEL_FAST_COPY=${SAGR_HSAKMT_MODEL_FAST_COPY}"
  if [[ $engine == vllm ]]; then
    echo "# unchanged-upstream evidence"
    echo "vllm_head=$(git -C "${ROOT}/projects/vllm" rev-parse HEAD 2>/dev/null)"
    echo "vllm_dirty_files=$(git -C "${ROOT}/projects/vllm" status --porcelain -- . 2>/dev/null | wc -l)"
    echo "vllm_plugins_env=[${VLLM_PLUGINS}]"
    echo -n "gemsim_entry_points_in_site_packages="
    grep -l 'gemsim' "${PREFIX}"/lib/python3.12/site-packages/*.dist-info/entry_points.txt 2>/dev/null | wc -l
  else
    echo "sglang_dirty_files=$(git -C "${ROOT}/projects/sglang-0.5.17" status --porcelain -- . 2>/dev/null | wc -l)"
  fi
  echo "started=$(date -Is)"
  echo "--- run-identity-gate ---"
  python3 tools/run_identity_gate.py --format text 2>&1
} >"$log"

# --- the run ----------------------------------------------------------------
# This host exposes a real NVIDIA RTX 5090 through WSL. With the
# simulator-aware AMD SMI provider on the library path, upstream platform
# selection sees ROCm *and* CUDA and refuses to activate two platforms. Masking
# NVML in a private mount namespace is isolation, not a framework change, and
# the goal forbids any NVIDIA fallback in an accepted run.
: > /tmp/empty-nvml.so

if [[ -n $capsule ]]; then
  # A capsule proves something about the lanes only if it runs in the lanes'
  # exact environment and isolation, which is why it is dispatched from here
  # rather than from a script of its own.
  unshare -r -m bash -c '
    mount --bind /tmp/empty-nvml.so /usr/lib/wsl/lib/libnvidia-ml.so.1
    exec python "$@"
  ' _ "$capsule" >>"$log" 2>&1
  status=$?
elif [[ $engine == sglang ]]; then
  sglang_args=(
    --tp-size "$tp" --attention-backend aiter
    --context-length 16 --max-total-tokens 16 --max-mamba-cache-size 5
    --max-new-tokens 1 --watchdog-timeout 86400 --model-path "$model"
  )
  (( dummy_weights )) && sglang_args+=(--load-format dummy)
  unshare -r -m bash -c '
    mount --bind /tmp/empty-nvml.so /usr/lib/wsl/lib/libnvidia-ml.so.1
    exec python examples/sglang/qwen35_inference.py "$@"
  ' _ "${sglang_args[@]}" >>"$log" 2>&1
  status=$?
else
  vllm_args=(
    --tp-size "$tp" --model-path "$model"
    --context-length 16 --max-new-tokens 1 --max-num-seqs 1
  )
  (( dummy_weights )) && vllm_args+=(--load-format dummy)
  # A real file, not a heredoc: with tensor_parallel_size > 1 vLLM spawns
  # workers through multiprocessing, and spawn re-imports the parent __main__
  # from its recorded path. A stdin-fed program records "<stdin>", so every
  # worker dies with FileNotFoundError before touching the GPU.
  unshare -r -m bash -c '
    mount --bind /tmp/empty-nvml.so /usr/lib/wsl/lib/libnvidia-ml.so.1
    exec python examples/vllm/qwen35_inference.py "$@"
  ' _ "${vllm_args[@]}" >>"$log" 2>&1
  status=$?
fi

echo "finished=$(date -Is) status=${status}" >>"$log"
exit "$status"
